# Performance

##### Overview:
- **Teaching:** 5 min
- **Exercises:** 15 min

**Questions**
- How does using `numpy` help me write more efficient code?
- How can I find out how to check performance of codes in `Python`?

**Objectives**
- Know that `Numpy` and `SciPy` use a C or Fortran and make use of other standard libraries to support their built-in functions.
- Use `timeit` to time code execution.

## Timeit

Python has a convenient timing magic called `timeit`.

Can use this to measure the execution time of small code snippets.

* From python: `import timeit` and supply code  snippet as a string
* From ipython: can use magic command `%timeit`

By default, `%timeit` repeats the code 3 times and outputs the best time. It also tells you how many iterations it ran the code per repeat. 
You can specify the number of repeats and the number of iterations per repeat.
```
%timeit -n <iterations> -r <repeats>  <code_snippet>
```

See

* `%timeit?` for more information
* https://docs.python.org/3/library/timeit.html

First as always we must import `numpy`:

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

Let's create ourselves an array as before and change their shape.

In [2]:
nd = np.arange(100).reshape((10,10))

NameError: name 'np' is not defined

In [5]:
%%timeit


[[0 1 2 3 4]
 [5 6 7 8 9]]


Now we can begin to use `numpy` in 'happiness', ie use it to make our lives easier

In [6]:
c=0.1*a
print(c)

[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]


Now is `c` a copy of the original array or just a new view?

In [8]:
c[(0,0)] = -1
print(a)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[-1.   0.1  0.2  0.3  0.4]
 [ 0.5  0.6  0.7  0.8  0.9]]


In [7]:
c.base is a

False

## 'Multiplication'

Now that we have operated on a single array let's multiply to arrays together

In [9]:
print(a*b)

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


## Information: 

What has just happend?  This is not a vector or matrix multiplication but an element by element product.  What happens when the two arrays or vectors are not of the same shape, size or length?

## Dot product

If we want to perform a well defined operation such as a *dot* product then we need to construct this properly, for two (non-square) arrays of the same shape, the *dot* product is defined if:

$a \cdot b^T$

We can perform this using `numpy` with:

In [10]:
print(a.dot(b.T))

[[ 30  80]
 [ 80 255]]


## Exercise:

Calculate the cross product:

$a \times b^T$

for two arrays `[2,3,4]` and `[5,6,7]`

[Solution]()

## Solution+:

As you would expect there is a built in `numpy` function `cross` but its usage is slightly different that for the `dot` product.

In [17]:
p = np.array([2,3,4])
q = np.array([5,6,7])
np.cross(p,q)

array([-3,  6, -3])

If you want to understand why the *cross* product has a different form from the *dot* product you need can ask a mathematician ...

:Solution+

## Exercise: Explore

Take the time to explore other built-in numpy functions and mathematical operations.  As always, as far as possible we want to make use of existing functionality rather than reinvent the wheel.

## Key Points:
- Numpy allows you to perform vector operations on arrays without implicitly looping
- If you have two arrays `*` performs an element by element product
- Understanding how functions work, whether they operate on individual objects or the class is key to using `numpy` effectively